export const STATE = "STATE";
export const SET_SLOT = "SET_SLOT";
export const SET_SLOTS_COUNT = "SET_SLOTS_COUNT";
export const ADD_SLOT_TIME = "ADD_SLOT_TIME";
export const CLEAR_SLOT = "CLEAR_SLOT";
export const MUTE_SLOT = "MUTE_SLOT";
export const OPEN_SLOT_OPTIONS_MODAL = "OPEN_SLOT_OPTIONS_MODAL";
export const CLOSE_SLOT_OPTIONS_MODAL = "CLOSE_SLOT_OPTIONS_MODAL";